parameters:
  region:
    value: "foo"
    description: "Region setting"

shared:
  image: node:14
    
jobs:
  main:
    requires: [ ~commit, ~pr ]
    steps:
      - test: echo $SCM_URL
      - show: |
          echo "Region: $(meta get parameters.region.value)"
  detached:
    requires: []
    steps:
      - show: |
          echo "Region: $(meta get parameters.region.value)"
