parameters:
  region:
    value: "foo"
    description: "Region setting"

shared:
  image: node:18
    
jobs:
  main:
    annotations:
      screwdriver.cd/manualStartEnabled: false
    requires: [ ~commit, ~pr ]
    steps:
      - show: |
          echo "Region: $(meta get parameters.region.value)"
  detached:
    requires: [ ~commit, ~pr ]
    steps:
      - show: |
          echo "Region: $(meta get parameters.region.value)"
  join:
    requires: [ main, detached ]
    steps:
      - echo: echo hi
  disabled-check:
    requires: ~pr
    annotations:
      screwdriver.cd/jobDisabledByDefault: true
    steps:
      - echo: echo hi
