shared:
  image: node:20
    
jobs:
  main:
    parameters:
      region:
        value: "foo"
        description: "Region setting"
      prpram:
        value: "Add in PR Job"
    requires: [ ~commit, ~pr ]
    steps:
      - meta-get: |
          meta get test.hoge
          meta get parameters.region.value
          meta set test.hoge 'foooooo'
          meta get parameters.prpram.value

  prclosed-test:
    parameters:
      foo:
        value: "FOO"
        description: "job pram"
      bar: "BAR"
    requires: [ ~pr-closed ]
    steps:
      - get-param: |
          echo "param1: $(meta get parameters.foo.value)"
          echo "param2: $(meta get parameters.bar.value)"
          echo "PR-closed: $(meta get sd.pr.merged)"
