shared:
  image: node:20
    
jobs:
  main:
    annotations:
      screwdriver.cd/manualStartEnabled: false
    requires: [ ~commit, ~pr ]
    steps:
      - show: |
          echo "Region: $(meta get parameters.region.value)"
  detached:
    parameters:
      region:
        value: "foo"
        description: "Region setting"
    requires: [ ~commit, ~pr ]
    steps:
      - show: |
          echo "Region: $(meta get parameters.region.value)"
  join:
    requires: [ main, detached ]
    steps:
      - echo: echo hi
