shared:
  image: node:20
    
jobs:
  main:
    parameters:
      region:
        value: "foo"
        description: "Region setting"
    annotations:
    requires: [ ~commit, ~pr ]
    steps:
      - meta-get: |
          meta get test.hoge
          meta get parameters.region.value
          meta set test.hoge 'foooooo'
